server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /var/log/nginx/access.log  # Adjust if needed
  - job_name: nginx-error-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx_errors
          __path__: /var/log/nginx/error.log  # Adjust if needed